# Generated by Django 4.2.2 on 2023-06-26 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Employees', '0002_employee_age_employee_email_employee_phone'),
        ('Branches', '0003_branch_buildingnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Employees.employee'),
        ),
    ]
